server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main #le indico rama x defecto
          url: https://github.com/marcelawojtasik/BootcampJAVA.ConfigServer.git
          search-paths: config-data
  application:
    name: ConfigServer

